name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Export env
        run: |
          echo "NEXT_PUBLIC_NINJAS_API_KEY=${{ secrets.NEXT_PUBLIC_NINJAS_API_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_EMAILTO=${{ secrets.NEXT_PUBLIC_EMAILTO }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_EMAILJS_SERVICE_ID=${{ secrets.NEXT_PUBLIC_EMAILJS_SERVICE_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_EMAILJS_SUBSCRIPTION_ID_TEMPLATE=${{ secrets.NEXT_PUBLIC_EMAILJS_SUBSCRIPTION_ID_TEMPLATE }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_EMAILJS_BOOKING_ID_TEMPLATE=${{ secrets.NEXT_PUBLIC_EMAILJS_BOOKING_ID_TEMPLATE }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_MAPBOX_GL_KEY=${{ secrets.NEXT_PUBLIC_MAPBOX_GL_KEY }}" >> $GITHUB_ENV

      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright for update of missing snapshots
        # env:
        #   PLAYWRIGHT_BASE_URL: http://localhost:3000
        run: npm run pw:update
        continue-on-error: true

      - name: Run Playwright tests
        # env:
        #   PLAYWRIGHT_BASE_URL: http://localhost:3000
        run: npm run pw

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
